### ISSUE TITLE
📦️ Chore: PR 관련 Github Action 세팅

### ISSUE THREAD

**Issue by oris8** [codeit-2000/codeit-resources#18]
# 작업 설명

Auto Assign Reviewers and Assignees ? ? 어때요

```
name: Auto Assign Reviewers and Assignees

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  auto-assign:
    runs-on: ubuntu-latest

    steps:
      - name: Auto Assign Assignees and Reviewers
        uses: kentaro-m/auto-assign-action@v2.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          team-reviewers: 2000
          add-assignees: author
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```

## 세부 작업 목록

- [ ] Todo
- [ ] Todo
